# Classification

In [19]:
import pandas as pd
import numpy as np

class1 = pd.read_csv("classification.csv")

In [9]:
corr_matrix = class1.corr()

corr_matrix[corr_matrix >= 0.9].sum()

v_1       1.000000
v_2       1.000000
v_3       1.926209
v_4       1.000000
v_5       1.000000
v_6       1.000000
v_7       1.000000
v_8       1.000000
v_9       1.000000
v_10      1.000000
v_11      1.926209
v_12      1.000000
target    1.000000
dtype: float64

In [10]:
corr_matrix

,v_1,v_2,v_3,v_4,v_5,v_6,v_7,v_8,v_9,v_10,v_11,v_12,target
v_1,1.000000,0.358444,-0.291931,-0.333528,0.204706,0.182503,0.542077,0.192874,0.618609,-0.776538,-0.195194,-0.466388,0.129294
v_2,0.358444,1.000000,-0.192374,-0.322927,0.142711,0.765650,0.103451,-0.264760,-0.217733,-0.482656,-0.127969,-0.055539,0.559967
v_3,-0.291931,-0.192374,1.000000,-0.103415,-0.776988,-0.041681,0.360740,0.212378,-0.532305,0.021155,0.926209,-0.217091,-0.125574
v_4,-0.333528,-0.322927,-0.103415,1.000000,0.299495,-0.282172,-0.092524,0.376553,0.078786,0.129084,0.014002,-0.085106,-0.607962
v_5,0.204706,0.142711,-0.776988,0.299495,1.000000,0.278548,-0.207491,-0.325802,0.175219,0.151897,-0.494429,0.069827,0.007646
v_6,0.182503,0.765650,-0.041681,-0.282172,0.278548,1.000000,0.356563,-0.178429,-0.395594,-0.019067,0.104854,0.283439,0.355963
v_7,0.542077,0.103451,0.360740,-0.092524,-0.207491,0.356563,1.000000,0.693908,0.254606,-0.379219,0.404380,-0.099598,-0.279007
v_8,0.192874,-0.264760,0.212378,0.376553,-0.325802,-0.178429,0.693908,1.000000,0.527153,-0.245077,0.102050,0.066048,-0.613567
v_9,0.618609,-0.217733,-0.532305,0.078786,0.175219,-0.395594,0.254606,0.527153,1.000000,-0.408153,-0.602081,-0.080183,-0.285478
v_10,-0.776538,-0.482656,0.021155,0.129084,0.151897,-0.019067,-0.379219,-0.245077,-0.408153,1.000000,0.004716,0.708080,-0.141712
v_11,-0.195194,-0.127969,0.926209,0.014002,-0.494429,0.104854,0.404380,0.102050,-0.602081,0.004716,1.000000,-0.361245,-0.141878
v_12,-0.466388,-0.055539,-0.217091,-0.085106,0.069827,0.283439,-0.099598,0.066048,-0.080183,0.708080,-0.361245,1.000000,-0.015484
target,0.129294,0.559967,-0.125574,-0.607962,0.007646,0.355963,-0.279007,-0.613567,-0.285478,-0.141712,-0.141878,-0.015484,1.000000

In [5]:
class1.describe()

,v_1,v_2,v_3,v_4,v_5,v_6,v_7,v_8,v_9,v_10,v_11,v_12,target
count,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000
mean,-0.511946,0.029368,0.102888,-0.157062,-1.061615,-1.202088,-0.557339,0.706537,0.486094,-0.649257,-0.642308,0.026067,0.550556
std,3.157810,1.751569,2.003690,1.611714,1.426915,2.053804,1.632385,2.726397,1.644239,1.855859,1.869548,1.524047,0.497576
min,-12.525340,-5.231960,-6.597090,-4.896670,-5.867850,-6.448870,-5.652650,-7.760350,-4.825480,-6.512840,-7.047690,-4.202530,0.000000
25%,-2.680907,-1.168230,-1.179710,-1.274385,-2.003583,-2.624455,-1.718805,-1.284353,-0.586963,-1.936177,-1.865870,-1.096765,0.000000
50%,-0.593210,-0.082700,0.148440,-0.242765,-1.066085,-1.328955,-0.562480,0.884630,0.569110,-0.541495,-0.555150,-0.029350,1.000000
75%,1.801338,1.262868,1.509780,0.938377,-0.128780,0.092840,0.569145,2.811808,1.632197,0.682680,0.694340,1.141643,1.000000
max,9.522590,6.302680,6.060580,6.844090,3.756250,6.100570,4.435020,8.434730,6.738850,4.648430,5.040900,5.771390,1.000000

In [21]:
class1.drop("v_11", axis=1, inplace=True) #v_3 and v_11 are highly correlated.

In [22]:
from sklearn.model_selection import KFold, cross_val_score, train_test_split, cross_validate
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, make_scorer


def crossval(model, data, scoring="accuracy", n_splits=5, SEED=301, scaler=False):
    if scaler:
        pipe = Pipeline([('scaler', MinMaxScaler()), ('clf', model)])
    else:
        pipe=model
    np.random.seed(SEED)
    x_total = data.iloc[:, :-1]
    y_total = data.iloc[:, -1]

    kfold = KFold(n_splits=5, shuffle=True, random_state=SEED)
    cvscore = cross_val_score(pipe, x_total, y_total, cv=kfold, scoring=scoring)
    std = cvscore.std()
    mean = cvscore.mean()

    print(f"Intervalo: [{100*(mean-2*std)}, {100*(mean+2*std)}]\nMédia: {100*mean}")

crossval(RandomForestClassifier(), class1)

Intervalo: [92.67343456504604, 96.77100987939843]
Média: 94.72222222222223